### ISSUE TITLE
Use more specific `activationEvents`

### ISSUE THREAD

**Issue by neilsustc** [ritwickdey/LiveServer-VScodeExtension#1]
This extension is activated all the time. As a result, the status bar item is always visible.

I think we can use multiple `activationEvents` like `"workspaceContains: **/*.html"`, `"workspaceContains: _config.yml"` and something else.

**Comment by ritwickdey** [comment]
First, _Thanks You Very Much for the suggestion._ 

yep, you're right. that should not be activated if there are no HTML file in work-space. Because this is meaning less.

okay! I have changed `activationEvents ` to `"workspaceContains:**/*.html"`, `"onLanguage:html"`.

**Comment by ritwickdey** [comment]
I think, we should not block `activationEvents `  for `onCommand:extension.liveServer.goOnline`. 

In case if anyone wants to start a server for a unknown reason......... :p .......

**Comment by neilsustc** [comment]
😁

**Comment by neilsustc** [comment]
Another small suggestion 😉.
It seems that vscode extensions are usually named in the format of `vscode-lowercase-name`. 
Personally I think it looks better than name of mixed upper and lower case chars.

This is a picture from the vscode official iteration plan

![image](https://user-images.githubusercontent.com/7588612/27768007-cf586b76-5f3a-11e7-9948-42b15730ca79.png)

**Comment by ritwickdey** [comment]
Sorry! I don't understand. Did you mean about the naming convention of git repo?

**Comment by neilsustc** [comment]
Yes, the name of git repo ...

**Comment by ritwickdey** [comment]
okay. I got that. I'll update that tonight 👍

**Comment by ritwickdey** [comment]
I updated the name. Is that okay?

**Comment by neilsustc** [comment]
Now it's perfect

**Comment by ritwickdey** [comment]
okay! I got another issue. `workspaceContains` checks also node_modules. Can I exclude it?

**Comment by neilsustc** [comment]
😮

It supports glob patterns. You can try `!node_modules/**/*`.

If it doesn't work, maybe we should open a vscode issue. (And this is the original [PR](https://github.com/Microsoft/vscode/pull/24570))

**Comment by ritwickdey** [comment]
`workspaceContains:**/*.html",
"workspaceContains:!node_modules/**/*,`

even if I write this, extension will be activated because of the first line.

**Comment by neilsustc** [comment]
I would suggest that we should stop use `**/*.html`, it's too general. And that means we require there is at least a HTML file in the root folder.

We can add more patterns for common web project structure later

**Comment by ritwickdey** [comment]
but if we don't use `**/*.html` , then it will show every time.

**Comment by neilsustc** [comment]
I guess that's because you still have `!node_modules/**/*` 😳

I mean

```json
"activationEvents": [
    "workspaceContains:*.html",
    "onLanguage:html",
    "onCommand:extension.liveServer.goOnline",
    "onCommand:extension.liveServer.goOffline"
]
```

**Comment by ritwickdey** [comment]
`"workspaceContains:*.html",`  => that will not work for sub folders.

Anyway, I am able to restrict that by code. :)

**Comment by neilsustc** [comment]
👌
